name: Bug Report
description: Something is not working
title: ""
labels: [bug]

body:
  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmation
      options:
        - label: I searched existing issues and discussions, and I checked the internet for the error messages
          required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Minimal Module Configuration
      description: Show the smallest possible config that reproduces the issue (redact secrets)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Output
      description: terraform plan/apply errors, logs, or stack traces
      render: shell
